name: zendvo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8

  # Navigation
  go_router: ^14.6.2

  # Utilities
  dartz: ^0.10.1
  stellar_flutter_sdk: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  fonts:
    - family: BR Firma
      fonts:
        - asset: assets/fonts/br-firma/BR Firma Thin.otf
          weight: 100
        - asset: assets/fonts/br-firma/BR Firma Thin Italic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Extra Light.otf
          weight: 200
        - asset: assets/fonts/br-firma/BR Firma Extra Light Italic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Light.otf
          weight: 300
        - asset: assets/fonts/br-firma/BR Firma Light Italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Regular.otf
          weight: 400
        - asset: assets/fonts/br-firma/BR Firma Regular Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Medium.otf
          weight: 500
        - asset: assets/fonts/br-firma/BR Firma Medium Italic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/br-firma/BR Firma SemiBold.otf
          weight: 600
        - asset: assets/fonts/br-firma/BR Firma SemiBold Italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Bold.otf
          weight: 700
        - asset: assets/fonts/br-firma/BR Firma Bold Italic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/br-firma/BR Firma Black.otf
          weight: 900
        - asset: assets/fonts/br-firma/BR Firma Black Italic.otf
          weight: 900
          style: italic
